#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# source environment file if exists
if [[ -f "$SCRIPT_DIR/.env" ]]; then
  . "$SCRIPT_DIR/.env"
fi

REDREAM_DIR=${REDREAM_DIR:-$HOME/Applications/redream}

if uname | grep -q MSYS; then
  PLATFORM="windows"
  APP_PATH="redream"
  LINK_TARGET="..\.."
elif uname | grep -q Darwin; then
  PLATFORM="mac"
  APP_PATH="redream.app/Contents/MacOS/redream"
  LINK_TARGET="../../../../.."
else
  PLATFORM="linux"
  APP_PATH="redream"
  LINK_TARGET="../.."
fi

get_latest_url() {
  local REDREAM_BASE_URL="https://redream.io"

  curl -Sso /tmp/redream-download.html "$REDREAM_BASE_URL/download"

  local links=$(
    grep -E 'href="([^"]*redream.x86_64-'$PLATFORM'[^"]+)' /tmp/redream-download.html |
      sed -E 's/.*href="([^"]*redream.x86_64-'$PLATFORM'[^"]+)".*/\1/g' |
      uniq
  )

  rm /tmp/redream-download.html

  local latest=$(echo "$links" | sort -rV | head -n1)
  echo "${REDREAM_BASE_URL}${latest}"
}

download() {
  echo -n "Downloading $1 ... "
  if [[ -f "$2" ]]; then
    echo "SKIP"
  else
    mkdir -p "$(dirname "$2")"
    if curl -Sso "$2" "$1"; then
      echo "OK"
    else
      rm -f "$2"
      echo "ERROR"
    fi
  fi
}

extract() {
  echo -n "Extracting $1 ... "
  if [[ -d "$2" ]]; then
    echo "SKIP"
  else
    mkdir -p "$2"
    if [[ "$PLATFORM" == "windows" ]]; then
      if unzip -q "$1" -d "$2"; then
        echo "OK"
      else
        rmdir "$2"
        echo "ERROR"
      fi
    else
      if tar xf "$1" -C "$2"; then
        echo "OK"
      else
        rmdir "$2"
        echo "ERROR"
      fi
    fi
  fi
}

link_release() {
  echo -n "Creating hardlink to the latest release ... "

  if [[ -f "$REDREAM_DIR/redream" ]] || [[ -f "$REDREAM_DIR/redream.exe" ]]; then
    rm -f "$REDREAM_DIR/redream"
  fi

  cd "$release_path/$(dirname "$APP_PATH")"

  if [[ "$PLATFORM" == "windows" ]]; then
    if cmd.exe /c "mklink /h "'"'$LINK_TARGET\\redream.exe'"'" redream.exe" >/dev/null; then
      echo "OK"
    else
      cp "redream.exe" "$REDREAM_DIR/redream.exe"
      echo "ERROR"
    fi
  else
    if echo "$(basename "$APP_PATH")" | cpio -p -al "$LINK_TARGET"; then
      echo "OK"
    else
      cp "redream" "$REDREAM_DIR/redream"
      echo "ERROR"
    fi
  fi

  cd - >/dev/null
}

create_macos_application() {
  echo -n "Creating macOS redream.app in ~/Applications ... "
  if [[ -d ~/Applications/redream.app ]]; then
    echo "SKIP"
    return
  fi
  mkdir -p ~/Applications/redream.app/Contents/{MacOS,Resources}
  echo -e "#!/bin/sh\nexec $REDREAM_DIR/redream "$@ >~/Applications/redream.app/Contents/MacOS/redream
  chmod +x ~/Applications/redream.app/Contents/MacOS/redream
  chmod +x ~/Applications/redream.app
  cp "$release_path/redream.app/Contents/Resources/icon.icns" ~/Applications/redream.app/Contents/Resources
  cp "$release_path/redream.app/Contents/Info.plist" ~/Applications/redream.app/Contents
  echo "OK"
}

create_linux_desktop_launcher() {
  local shortcut_text
  local shortcut_path
  shortcut_text=$(cat <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=redream
Icon=$REDREAM_DIR/redream.png
Exec=$REDREAM_DIR/redream %f
Categories=Game;Emulator;
Terminal=false
EOF
)
  echo -n "Creating linux redream.desktop in ~/.local/share/applications/redream.desktop ... "
  if [[ -f ~/.local/share/applications/redream.desktop ]] \
      && [[ "$shortcut_text" == "$(cat ~/.local/share/applications/redream.desktop)" ]] \
  ; then
    echo "SKIP ... EXISTS"
    return
  fi
  if [[ ! -d ~/.local/share/applications ]]; then
    echo "ERR ... DIR NOT FOUND ~/.local/share/applications"
    return
  fi
  wget -qO "$REDREAM_DIR/redream.png" https://raw.githubusercontent.com/andrewmackrodt/redream-launcher/master/redream.png
  echo "$shortcut_text" >~/.local/share/applications/redream.desktop
  echo "OK"
}

update() {
  local latest_url
  local download_path
  local release_path

  # get the latest release
  latest_url=$(get_latest_url)
  download_path="$REDREAM_DIR/releases/$(basename "$latest_url")"
  release_path="$REDREAM_DIR/releases/$(basename "$latest_url" | sed -E 's/.+-(v.+)\.(tar\.gz|zip)/\1/')"

  # download and extract
  download "$latest_url" "$download_path"
  extract "$download_path" "$release_path"

  # check for existence of redream binary
  if [[ ! -f "$release_path/$APP_PATH" ]]; then
    echo "ERROR could not locate redream executable in release"
    exit 1
  fi

  # create a hardlink to the latest release
  link_release

  if [[ "$PLATFORM" == "mac" ]]; then
    create_macos_application
  elif [[ "$PLATFORM" == "linux" ]]; then
    create_linux_desktop_launcher
  fi
}

if [[ $* != *"no-update"* ]]; then
  update
fi

if [[ $* != *"no-run"* ]]; then
  exec "$REDREAM_DIR/redream" "$@"
fi
